require 'rubygems'
require 'rake'
Rake::TaskManager.record_task_metadata = true

task :default => :help

desc "Show this help"
task :help do
  puts "Usage:"
  Rake.application.options.show_tasks = :tasks
  Rake.application.options.show_task_pattern = //
  Rake.application.display_tasks_and_comments()
end

namespace 'test_server' do
  server_actions = {
    :run => {
      :desc => 'Run the test server',
      :args => 'start',
    },
    :start => {
      :desc => 'Start the test server and put it to background',
      :args => ['start', '--daemonize'],
    },
    :stop => {
      :desc => 'Stop the test server running in the background',
      :args => 'stop',
    },
  }

  server_actions.each do |name, options|
    desc options[:desc]
    task name do
      webserver_path = File.expand_path('test_server', File.dirname(__FILE__))
      command = [
        'thin', options[:args],
        "--chdir \"#{webserver_path}\""
      ]
      if [:start, :run].include? name
        cert_dir = File.join(webserver_path, 'cert')
        command += [
          "--rackup \"#{File.join(webserver_path, 'config', 'main.ru')}\"",
          "--ssl",
          "--ssl-key \"#{File.join(cert_dir, 'server.key')}\"",
          "--ssl-cert \"#{File.join(cert_dir, 'server.crt')}\""
        ]
      end
      command = command.flatten.compact.join(' ')
      sh *command
    end
  end

  desc 'Restart the test server running in the background'
  task :restart do |t|
    Rake::Task[Rake::Task.scope_name(t.scope, 'stop')].invoke
    Rake::Task[Rake::Task.scope_name(t.scope, 'start')].invoke
  end
end

namespace 'tests' do
  desc 'run all tests'
  task 'run', :prefix do |t, args|
    main_path = File.dirname(__FILE__)
    executable = if args[:prefix]
      File.expand_path(File.join(args[:prefix], 'share', 'libetpan', 'tests', 'low-level', 'test_oxws'), Dir.pwd)
    else
      File.expand_path('test_oxws', main_path)
    end
    ssl_cert = File.expand_path(File.join('test_server', 'cert', 'server.crt'), main_path)
    command = [
      File.expand_path(executable, main_path),
      "--ssl-cert \"#{ssl_cert}\""
    ].flatten.compact.join(' ')
    sh *command
  end
end

desc 'start test server and perform all tests'
task 'run', :prefix do |t, args|
  begin
    puts '### Starting test server ...'
    Rake::Task['test_server:start'].invoke
    sleep 1

    puts
    puts '### Running tests ...'
    Rake::Task['tests:run'].invoke(args[:prefix])
  ensure
    puts
    puts '### Shutting down test server ...'
    Rake::Task['test_server:stop'].invoke
  end
end
